export default [
  "stille/flau vind",
  "stille/flau vind",
  "svak vind",
  "svak vind",
  "lett bris",
  "lett bris",
  "lett bris",
  "laber bris",
  "laber bris",
  "laber bris",
  "frisk bris",
  "frisk bris",
  "liten kuling",
  "liten kuling",
  "liten kuling",
  "stiv kuling",
  "stiv kuling",
  "sterk kuling",
  "sterk kuling",
  "sterk kuling",
  "sterk kuling",
  "sterk kuling",
  "liten storm",
  "liten storm",
  "liten storm",
  "full storm",
  "full storm",
  "full storm",
  "full storm",
  "full storm",
  "sterk storm",
  "sterk storm",
  "sterk storm",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
  "orkan",
]
